#!/bin/bash

echo "🚀 Deploying Axis Thorn to Production"
echo "====================================="
echo ""
echo "Step 1: Deploy API to Render"
echo "----------------------------"
echo "Visit: https://render.com/deploy?repo=https://github.com/Gage5977/AxisThorn-website"
echo ""
echo "Or manually:"
echo "1. Go to https://dashboard.render.com"
echo "2. New > Blueprint"
echo "3. Connect GitHub: Gage5977/AxisThorn-website"
echo "4. Use branch: main"
echo "5. Blueprint path: api-deployment/render.yaml"
echo ""
echo "Deployment will create:"
echo "- API Service: axis-thorn-api"
echo "- PostgreSQL: axis-thorn-db"
echo "- Redis: axis-thorn-redis"
echo ""
echo "Step 2: Update Frontend (after API is deployed)"
echo "-----------------------------------------------"
echo "1. Note your Render API URL (e.g., https://axis-thorn-api.onrender.com)"
echo "2. Add to Vercel: NEXT_PUBLIC_API_URL = [your-api-url]"
echo "3. Redeploy Vercel"
echo ""
echo "Step 3: Verify Everything Works"
echo "-------------------------------"
./api-deployment/verify-deployment.sh https://axis-thorn-api.onrender.com