#!/bin/bash

echo "📦 Updating Vercel Environment Variables"
echo "======================================="
echo ""
echo "Please add the following to your Vercel project:"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select your project: axis-thorn-llc-website"
echo "3. Go to Settings > Environment Variables"
echo "4. Add:"
echo ""
echo "NEXT_PUBLIC_API_URL = https://axis-thorn-api.onrender.com"
echo ""
echo "5. Redeploy your frontend for changes to take effect"
echo ""
echo "To redeploy:"
echo "git commit --allow-empty -m 'Trigger Vercel redeploy'"
echo "git push origin main"