name: Deploy API to Render

on:
  push:
    branches: [main]
    paths:
      - 'api-deployment/**'
      - '.github/workflows/deploy-api-render.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": true}'
          
      - name: Wait for deployment
        run: sleep 60
        
      - name: Verify deployment
        run: |
          curl -f https://axis-thorn-api.onrender.com/api/health || exit 1